add_newline = false

format = "$directory$git_branch$git_status$character"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
truncation_length = 4
truncate_to_repo = true

[git_branch]
symbol = " "

[git_status]
style = "bold purple"

[cmd_duration]
min_time = 2000

[package]
disabled = true

[username]
disabled = true

[hostname]
disabled = true
